practices:
  JavaScript.LoggerUsed: off
  JavaScript.PackageJsonConfigurationSetCorrectly: off
  JavaScript.ESLintUsed: off
  JavaScript.ESLintWithoutErrorsPractice: off
  JavaScript.TypeScriptUsed: off
  JavaScript.DependenciesVersionMajorLevel: off
  JavaScript.DependenciesVersionMinorPatchLevel: off
  JavaScript.PrettierUsed: off
  LanguageIndependent.ReadmeIsPresent: off
  LanguageIndependent.EditorConfigIsPresent: off